name: C/C++ CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-22.04
    strategy:
      matrix:
        CXX: [g++-11, g++-12, g++-13, clang-15, clang-16]
    steps:
    - uses: actions/checkout@v3
    - name: install env
      run: |
        wget --no-check-certificate -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
        sudo add-apt-repository 'deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy main'
        sudo apt install ${{matrix.CXX}} ${{ fromJson('{ "clang-15": "libc++-15-dev libc++abi-15-dev", "clang-16": "libc++-16-dev libc++abi-16-dev" }')[matrix.CXX] }}
    - name: make
      run: make
      env:
        CXX: ${{ matrix.CXX }}
    - name: run
      run: ./hello
