name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-22.04
    strategy:
      matrix:
        CXX: [g++-11, g++-12, clang++-13, clang++-14]
    steps:
    - uses: actions/checkout@v3
    - name: install env
      run: wget https://github.com/nlohmann/json/releases/download/v3.11.2/json.hpp
    - name: make
      run: make
      env:
        CXX: ${{ matrix.CXX }}

