name: C/C++ CI

on:
  push:
    branches: [ * ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-22.04
    strategy:
      matrix:
        CXX: [g++-11, g++-12, clang++-13, clang++-14]
    steps:
    - uses: actions/checkout@v3
    - name: install env
      run: echo ''#sudo apt install g++-11
    - name: make
      run: make
      env:
        CXX: ${{ matrix.CXX }}

